title: Pages page
author: Alistair
email: alistair@example.com 
description: A site I made while on the official Pages tutorial 

baseurl: / 

theme: minima 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
